-- 이 시점(Flyway 도입 시점)의 실제 운영 스키마를 그대로 캡처한 베이스라인.
-- 기존 DB(이미 이 스키마가 있음)에서는 baseline-on-migrate에 의해 실행이
-- 건너뛰어지고, 완전히 새 DB에서는 이 파일이 그대로 실행되어 스키마를
-- 처음부터 만든다.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE jeju_place (
    id bigint NOT NULL,
    address character varying(255),
    category character varying(255),
    description text,
    embedding text,
    lat double precision,
    lng double precision,
    main_category character varying(255),
    name character varying(255),
    region character varying(255),
    sub_region character varying(255)
);

ALTER TABLE jeju_place ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME jeju_place_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE wishlist (
    id bigint NOT NULL,
    address character varying(255),
    category character varying(255),
    kakao_place_id character varying(255),
    lat double precision,
    lng double precision,
    name character varying(255)
);

ALTER TABLE wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE jeju_place ADD CONSTRAINT jeju_place_pkey PRIMARY KEY (id);
ALTER TABLE wishlist ADD CONSTRAINT wishlist_pkey PRIMARY KEY (id);

CREATE INDEX idx_jeju_place_region_category ON jeju_place USING btree (region, main_category);
